const List<Map<String, dynamic>> interestList = [
  {'name': 'Music', 'emoji': '🎷'},
  {'name': 'Fashion', 'emoji': '👕'},
  {'name': 'Photographer', 'emoji': '📷'},
  {'name': 'Pet', 'emoji': '🐈'},
  {'name': 'Travelling', 'emoji': '🛩️'},
  {'name': 'Technology', 'emoji': '💻'},
  {'name': 'Beauty', 'emoji': '🤩'},
  {'name': 'Food', 'emoji': '🍱'},
  {'name': 'Comedy', 'emoji': '🤣'},
  {'name': 'Skincare', 'emoji': '💄'},
  {'name': 'Wellness', 'emoji': '🧘🏾‍♂️'},
  {'name': 'Bag', 'emoji': '🎒'},
  {'name': 'Accessories', 'emoji': '⌚️'},
  {'name': 'Architecture', 'emoji': '🏠'},
  {'name': 'Art', 'emoji': '🖊️'},
  {'name': 'Sport', 'emoji': '⚽️'},
  {'name': 'Film', 'emoji': '🎬'},
  {'name': 'Drama', 'emoji': '🥹'},
];
