final countriesEnglish = <Map<String, dynamic>>[
  {
    'name': 'Afghanistan',
    'dial_code': '+93',
    'code': 'AF',
    'language': ['Pashto', 'Dari'],
    'nationality': 'Afghan',
  },
  {
    'name': 'Albania',
    'dial_code': '+355',
    'code': 'AL',
    'language': ['Albanian'],
    'nationality': 'Albanian',
  },
  {
    'name': 'Algeria',
    'dial_code': '+213',
    'code': 'DZ',
    'language': ['Tamazight'],
    'nationality': 'Algerian',
  },
  {
    'name': 'American Samoa',
    'dial_code': '+1684',
    'code': 'AS',
    'language': ['Samoan'],
    'nationality': 'American Samoan',
  },
  {
    'name': 'Andorra',
    'dial_code': '+376',
    'code': 'AD',
    'language': ['Catalan'],
    'nationality': 'Andorran',
  },
  {
    'name': 'Angola',
    'dial_code': '+244',
    'code': 'AO',
    'language': ['Kongo', 'Chokwe', 'Umbundu'],
    'nationality': 'Angolan',
  },
  {
    'name': 'Anguilla',
    'dial_code': '+1264',
    'code': 'AI',
    'language': <String>[],
    'nationality': 'Anguillan',
  },
  {
    'name': 'Antigua and Barbuda',
    'dial_code': '+1268',
    'code': 'AG',
    'language': <String>[],
    'nationality': 'Antiguan or Barbudan',
  },
  {
    'name': 'Argentina',
    'dial_code': '+54',
    'code': 'AR',
    'language': ['Guarani', 'Quechua', 'Mapudungun'],
    'nationality': 'Argentine',
  },
  {
    'name': 'Armenia',
    'dial_code': '+374',
    'code': 'AM',
    'language': ['Armenian'],
    'nationality': 'Armenian',
  },
  {
    'name': 'Aruba',
    'dial_code': '+297',
    'code': 'AW',
    'language': ['Dutch', 'Papiamento'],
    'nationality': 'Aruban',
  },
  {
    'name': 'Australia',
    'dial_code': '+61',
    'code': 'AU',
    'language': ['Australian Aboriginal languages'],
    'nationality': 'Australian',
  },
  {
    'name': 'Austria',
    'dial_code': '+43',
    'code': 'AT',
    'language': ['Austrian Slovene', 'Burgenland Croatian', 'Austro-Bavarian'],
    'nationality': 'Austrian',
  },
  {
    'name': 'Azerbaijan',
    'dial_code': '+994',
    'code': 'AZ',
    'language': ['Azerbaijani'],
    'nationality': 'Azerbaijani',
  },
  {
    'name': 'Bahamas',
    'dial_code': '+1242',
    'code': 'BS',
    'language': <String>[],
    'nationality': 'Bahamian',
  },
  {
    'name': 'Bahrain',
    'dial_code': '+973',
    'code': 'BH',
    'language': ['Arabic - BH'],
    'nationality': 'Bahraini',
  },
  {
    'name': 'Bangladesh',
    'dial_code': '+880',
    'code': 'BD',
    'language': ['Bengali'],
    'nationality': 'Bangladeshi',
  },
  {
    'name': 'Barbados',
    'dial_code': '+1246',
    'code': 'BB',
    'language': ['Bajan'],
    'nationality': 'Barbadian',
  },
  {
    'name': 'Belarus',
    'dial_code': '+375',
    'code': 'BY',
    'language': ['Belarusian'],
    'nationality': 'Belarusian',
  },
  {
    'name': 'Belgium',
    'dial_code': '+32',
    'code': 'BE',
    'language': ['Dutch'],
    'nationality': 'Belgian',
  },
  {
    'name': 'Belize',
    'dial_code': '+501',
    'code': 'BZ',
    'language': ['Mayan'],
    'nationality': 'Belizean',
  },
  {
    'name': 'Benin',
    'dial_code': '+229',
    'code': 'BJ',
    'language': ['Fon'],
    'nationality': 'Beninese',
  },
  {
    'name': 'Bermuda',
    'dial_code': '+1441',
    'code': 'BM',
    'language': <String>[],
    'nationality': 'Bermudian',
  },
  {
    'name': 'Bhutan',
    'dial_code': '+975',
    'code': 'BT',
    'language': ['Dzongkha'],
    'nationality': 'Bhutanese',
  },
  {
    'name': 'Bolivia, Plurinational State of',
    'dial_code': '+591',
    'code': 'BO',
    'language': ['Quechua', 'Aymara'],
    'nationality': 'Bolivian',
  },
  {
    'name': 'Bosnia and Herzegovina',
    'dial_code': '+387',
    'code': 'BA',
    'language': ['Bosnian', 'Croatian', 'Serbian'],
    'nationality': 'Bosnian or Herzegovinian',
  },
  {
    'name': 'Botswana',
    'dial_code': '+267',
    'code': 'BW',
    'language': ['Tswana'],
    'nationality': 'Batswana',
  },
  {
    'name': 'Brazil',
    'dial_code': '+55',
    'code': 'BR',
    'language': ['Portuguese - BR'],
    'nationality': 'Brazilian',
  },
  {
    'name': 'British Indian Ocean Territory',
    'dial_code': '+246',
    'code': 'IO',
    'language': <String>[],
    'nationality': 'BIOT',
  },
  {
    'name': 'Brunei Darussalam',
    'dial_code': '+673',
    'code': 'BN',
    'language': ['Malay'],
    'nationality': 'Bruneian',
  },
  {
    'name': 'Bulgaria',
    'dial_code': '+359',
    'code': 'BG',
    'language': ['Bulgarian'],
    'nationality': 'Bulgarian',
  },
  {
    'name': 'Burkina Faso',
    'dial_code': '+226',
    'code': 'BF',
    'language': ['Moore', 'Dioula'],
    'nationality': 'Burkinabe',
  },
  {
    'name': 'Burundi',
    'dial_code': '+257',
    'code': 'BI',
    'language': ['Kirundi'],
    'nationality': 'Burundian',
  },
  {
    'name': 'Cambodia',
    'dial_code': '+855',
    'code': 'KH',
    'language': ['Khmer'],
    'nationality': 'Cambodian',
  },
  {
    'name': 'Cameroon',
    'dial_code': '+237',
    'code': 'CM',
    'language': <String>[],
    'nationality': 'Cameroonian',
  },
  {
    'name': 'Canada',
    'dial_code': '+1',
    'code': 'CA',
    'language': ['English - CA', 'French - CA', 'Various Indigenous languages'],
    'nationality': 'Canadian',
  },
  {
    'name': 'Cape Verde',
    'dial_code': '+238',
    'code': 'CV',
    'language': ['Kriolu'],
    'nationality': 'Cape Verdean',
  },
  {
    'name': 'Cayman Islands',
    'dial_code': '+1345',
    'code': 'KY',
    'language': <String>[],
    'nationality': 'Caymanian',
  },
  {
    'name': 'Central African Republic',
    'dial_code': '+236',
    'code': 'CF',
    'language': ['Sango'],
    'nationality': 'Central African',
  },
  {
    'name': 'Chad',
    'dial_code': '+235',
    'code': 'TD',
    'language': ['Arabic - TD'],
    'nationality': 'Chadian',
  },
  {
    'name': 'Chile',
    'dial_code': '+56',
    'code': 'CL',
    'language': ['Mapudungun'],
    'nationality': 'Chilean',
  },
  {
    'name': 'China',
    'dial_code': '+86',
    'code': 'CN',
    'language': ['Standard Chinese', 'Cantonese', 'Mandarin', 'Shanghainese'],
    'nationality': 'Chinese',
  },
  {
    'name': 'Christmas Island',
    'dial_code': '+61',
    'code': 'CX',
    'language': <String>[],
    'nationality': 'Christmas Islander',
  },
  {
    'name': 'Cocos (Keeling) Islands',
    'dial_code': '+61',
    'code': 'CC',
    'language': <String>[],
    'nationality': 'Cocos Islander',
  },
  {
    'name': 'Colombia',
    'dial_code': '+57',
    'code': 'CO',
    'language': ['Spanish - CO'],
    'nationality': 'Colombian',
  },
  {
    'name': 'Comoros',
    'dial_code': '+269',
    'code': 'KM',
    'language': ['Comorian'],
    'nationality': 'Comoran',
  },
  {
    'name': 'Congo',
    'dial_code': '+242',
    'code': 'CG',
    'language': ['Lingala'],
    'nationality': 'Congolese',
  },
  {
    'name': 'Congo, The Democratic Republic of the',
    'dial_code': '+243',
    'code': 'CD',
    'language': ['Kikongo', 'Kiswahili', 'Tshiluba'],
    'nationality': 'Congolese',
  },
  {
    'name': 'Cook Islands',
    'dial_code': '+682',
    'code': 'CK',
    'language': ['Cook Islands Maori'],
    'nationality': 'Cook Islander',
  },
  {
    'name': 'Costa Rica',
    'dial_code': '+506',
    'code': 'CR',
    'language': <String>[],
    'nationality': 'Costa Rican',
  },
  {
    'name': 'Croatia',
    'dial_code': '+385',
    'code': 'HR',
    'language': ['Croatian'],
    'nationality': 'Croatian',
  },
  {
    'name': 'Cuba',
    'dial_code': '+53',
    'code': 'CU',
    'language': <String>[],
    'nationality': 'Cuban',
  },
  {
    'name': 'Cyprus',
    'dial_code': '+357',
    'code': 'CY',
    'language': ['Greek - CY', 'Cypriot'],
    'nationality': 'Cypriot',
  },
  {
    'name': 'Czech Republic',
    'dial_code': '+420',
    'code': 'CZ',
    'language': ['Czech'],
    'nationality': 'Czech',
  },
  {
    'name': 'Denmark',
    'dial_code': '+45',
    'code': 'DK',
    'language': ['Danish'],
    'nationality': 'Danish',
  },
  {
    'name': 'Djibouti',
    'dial_code': '+253',
    'code': 'DJ',
    'language': ['Somali'],
    'nationality': 'Djibouti',
  },
  {
    'name': 'Dominica',
    'dial_code': '+1767',
    'code': 'DM',
    'language': <String>[],
    'nationality': 'Dominican',
  },
  {
    'name': 'Dominican Republic',
    'dial_code': '+1 849',
    'code': 'DO',
    'language': <String>[],
    'nationality': 'Dominican',
  },
  {
    'name': 'Ecuador',
    'dial_code': '+593',
    'code': 'EC',
    'language': ['Quechua'],
    'nationality': 'Ecuadorian',
  },
  {
    'name': 'Egypt',
    'dial_code': '+20',
    'code': 'EG',
    'language': ['Arabic - EG'],
    'nationality': 'Egyptian',
  },
  {
    'name': 'El Salvador',
    'dial_code': '+503',
    'code': 'SV',
    'language': <String>[],
    'nationality': 'Salvadorian',
  },
  {
    'name': 'Equatorial Guinea',
    'dial_code': '+240',
    'code': 'GQ',
    'language': ['Fang', 'Bubi'],
    'nationality': 'Equatorial Guinean',
  },
  {
    'name': 'Eritrea',
    'dial_code': '+291',
    'code': 'ER',
    'language': ['Tigrinya'],
    'nationality': 'Eritrean',
  },
  {
    'name': 'Estonia',
    'dial_code': '+372',
    'code': 'EE',
    'language': ['Estonian'],
    'nationality': 'Estonian',
  },
  {
    'name': 'Ethiopia',
    'dial_code': '+251',
    'code': 'ET',
    'language': ['Oromo', 'Amharic', 'Tigrinya'],
    'nationality': 'Ethiopian',
  },
  {
    'name': 'Falkland Islands (Malvinas)',
    'dial_code': '+500',
    'code': 'FK',
    'language': <String>[],
    'nationality': 'Falkland Islander',
  },
  {
    'name': 'Faroe Islands',
    'dial_code': '+298',
    'code': 'FO',
    'language': <String>[],
    'nationality': 'Faroese',
  },
  {
    'name': 'Fiji',
    'dial_code': '+679',
    'code': 'FJ',
    'language': <String>[],
    'nationality': 'Fijian',
  },
  {
    'name': 'Finland',
    'dial_code': '+358',
    'code': 'FI',
    'language': ['Swedish - FI', 'Finnish'],
    'nationality': 'Finnish',
  },
  {
    'name': 'France',
    'dial_code': '+33',
    'code': 'FR',
    'language': ['Breton', 'Corsican', 'Occitan'],
    'nationality': 'French',
  },
  {
    'name': 'French Guiana',
    'dial_code': '+594',
    'code': 'GF',
    'language': <String>[],
    'nationality': 'French Guianese',
  },
  {
    'name': 'French Polynesia',
    'dial_code': '+689',
    'code': 'PF',
    'language': ['Tahitian'],
    'nationality': 'French Polynesian',
  },
  {
    'name': 'Gabon',
    'dial_code': '+241',
    'code': 'GA',
    'language': ['Fang'],
    'nationality': 'Gabonese',
  },
  {
    'name': 'Gambia',
    'dial_code': '+220',
    'code': 'GM',
    'language': <String>[],
    'nationality': 'Gambian',
  },
  {
    'name': 'Georgia',
    'dial_code': '+995',
    'code': 'GE',
    'language': ['Georgian'],
    'nationality': 'Georgian',
  },
  {
    'name': 'Germany',
    'dial_code': '+49',
    'code': 'DE',
    'language': ['German - DE'],
    'nationality': 'German',
  },
  {
    'name': 'Ghana',
    'dial_code': '+233',
    'code': 'GH',
    'language': <String>[],
    'nationality': 'Ghanaian',
  },
  {
    'name': 'Gibraltar',
    'dial_code': '+350',
    'code': 'GI',
    'language': <String>[],
    'nationality': 'Gibraltar',
  },
  {
    'name': 'Greece',
    'dial_code': '+30',
    'code': 'GR',
    'language': ['Greek'],
    'nationality': 'Greek',
  },
  {
    'name': 'Greenland',
    'dial_code': '+299',
    'code': 'GL',
    'language': ['Greenlandic'],
    'nationality': 'Greenlandic',
  },
  {
    'name': 'Grenada',
    'dial_code': '+1473',
    'code': 'GD',
    'language': <String>[],
    'nationality': 'Grenadian',
  },
  {
    'name': 'Guadeloupe',
    'dial_code': '+590',
    'code': 'GP',
    'language': <String>[],
    'nationality': 'Guadeloupe',
  },
  {
    'name': 'Guam',
    'dial_code': '+1671',
    'code': 'GU',
    'language': ['Chamorro'],
    'nationality': 'Guamanian',
  },
  {
    'name': 'Guatemala',
    'dial_code': '+502',
    'code': 'GT',
    'language': ['Mayan languages'],
    'nationality': 'Guatemalan',
  },
  {
    'name': 'Guernsey',
    'dial_code': '+44',
    'code': 'GG',
    'language': <String>[],
    'nationality': 'Guernsey',
  },
  {
    'name': 'Guinea',
    'dial_code': '+224',
    'code': 'GN',
    'language': <String>[],
    'nationality': 'Guinean',
  },
  {
    'name': 'Guinea-Bissau',
    'dial_code': '+245',
    'code': 'GW',
    'language': ['Crioulo'],
    'nationality': 'Guinea-Bissauan',
  },
  {
    'name': 'Guyana',
    'dial_code': '+595',
    'code': 'GY',
    'language': <String>[],
    'nationality': 'Guyanese',
  },
  {
    'name': 'Haiti',
    'dial_code': '+509',
    'code': 'HT',
    'language': ['Haitian Creole'],
    'nationality': 'Haitian',
  },
  {
    'name': 'Honduras',
    'dial_code': '+504',
    'code': 'HN',
    'language': <String>[],
    'nationality': 'Honduran',
  },
  {
    'name': 'Hong Kong',
    'dial_code': '+852',
    'code': 'HK',
    'language': ['Cantonese'],
    'nationality': 'Hong Kongese',
  },
  {
    'name': 'Hungary',
    'dial_code': '+36',
    'code': 'HU',
    'language': ['Hungarian'],
    'nationality': 'Hungarian',
  },
  {
    'name': 'Iceland',
    'dial_code': '+354',
    'code': 'IS',
    'language': ['Icelandic'],
    'nationality': 'Icelandic',
  },
  {
    'name': 'India',
    'dial_code': '+91',
    'code': 'IN',
    'language': ['Hindi'],
    'nationality': 'Indian',
  },
  {
    'name': 'Indonesia',
    'dial_code': '+62',
    'code': 'ID',
    'language': ['Bahasa Indonesia'],
    'nationality': 'Indonesian',
  },
  {
    'name': 'Iran, Islamic Republic of',
    'dial_code': '+98',
    'code': 'IR',
    'language': ['Persian'],
    'nationality': 'Iranian',
  },
  {
    'name': 'Iraq',
    'dial_code': '+964',
    'code': 'IQ',
    'language': ['Arabic - IQ', 'Kurdish'],
    'nationality': 'Iraqi',
  },
  {
    'name': 'Ireland',
    'dial_code': '+353',
    'code': 'IE',
    'language': ['Irish'],
    'nationality': 'Irish',
  },
  {
    'name': 'Isle of Man',
    'dial_code': '+44',
    'code': 'IM',
    'language': <String>[],
    'nationality': 'Manx',
  },
  {
    'name': 'Israel',
    'dial_code': '+972',
    'code': 'IL',
    'language': ['Hebrew'],
    'nationality': 'Israeli',
  },
  {
    'name': 'Italy',
    'dial_code': '+39',
    'code': 'IT',
    'language': ['Italian'],
    'nationality': 'Italian',
  },
  {
    'name': 'Jamaica',
    'dial_code': '+1876',
    'code': 'JM',
    'language': <String>[],
    'nationality': 'Jamaican',
  },
  {
    'name': 'Japan',
    'dial_code': '+81',
    'code': 'JP',
    'language': ['Japanese'],
    'nationality': 'Japanese',
  },
  {
    'name': 'Jersey',
    'dial_code': '+44',
    'code': 'JE',
    'language': <String>[],
    'nationality': 'Jersey',
  },
  {
    'name': 'Jordan',
    'dial_code': '+962',
    'code': 'JO',
    'language': ['Arabic - JO'],
    'nationality': 'Jordanian',
  },
  {
    'name': 'Kazakhstan',
    'dial_code': '+7 7',
    'code': 'KZ',
    'language': ['Kazakh'],
    'nationality': 'Kazakh',
  },
  {
    'name': 'Kenya',
    'dial_code': '+254',
    'code': 'KE',
    'language': ['Kiswahili'],
    'nationality': 'Kenyan',
  },
  {
    'name': 'Kiribati',
    'dial_code': '+686',
    'code': 'KI',
    'language': ['Gilbertese'],
    'nationality': 'I-Kiribati',
  },
  {
    'name': "Korea, Democratic People's Republic of",
    'dial_code': '+850',
    'code': 'KP',
    'language': ['Korean'],
    'nationality': 'North Korean',
  },
  {
    'name': 'Korea, Republic of',
    'dial_code': '+82',
    'code': 'KR',
    'language': ['Korean'],
    'nationality': 'South Korean',
  },
  {
    'name': 'Kuwait',
    'dial_code': '+965',
    'code': 'KW',
    'language': ['Arabic - KW'],
    'nationality': 'Kuwaiti',
  },
  {
    'name': 'Kyrgyzstan',
    'dial_code': '+996',
    'code': 'KG',
    'language': ['Kyrgyz'],
    'nationality': 'Kyrgyz',
  },
  {
    'name': "Lao People's Democratic Republic",
    'dial_code': '+856',
    'code': 'LA',
    'language': ['Lao'],
    'nationality': 'Lao',
  },
  {
    'name': 'Latvia',
    'dial_code': '+371',
    'code': 'LV',
    'language': ['Latvian'],
    'nationality': 'Latvian',
  },
  {
    'name': 'Lebanon',
    'dial_code': '+961',
    'code': 'LB',
    'language': ['Arabic - LB'],
    'nationality': 'Lebanese',
  },
  {
    'name': 'Lesotho',
    'dial_code': '+266',
    'code': 'LS',
    'language': ['Southern Sotho'],
    'nationality': 'Mosotho',
  },
  {
    'name': 'Liberia',
    'dial_code': '+231',
    'code': 'LR',
    'language': <String>[],
    'nationality': 'Liberian',
  },
  {
    'name': 'Libyan Arab Jamahiriya',
    'dial_code': '+218',
    'code': 'LY',
    'language': <String>[],
    'nationality': 'Libyan',
  },
  {
    'name': 'Liechtenstein',
    'dial_code': '+423',
    'code': 'LI',
    'language': <String>[],
    'nationality': 'Liechtenstein',
  },
  {
    'name': 'Lithuania',
    'dial_code': '+370',
    'code': 'LT',
    'language': ['Lithuanian'],
    'nationality': 'Lithuanian',
  },
  {
    'name': 'Luxembourg',
    'dial_code': '+352',
    'code': 'LU',
    'language': ['Luxembourgish'],
    'nationality': 'Luxembourg',
  },
  {
    'name': 'Macao',
    'dial_code': '+853',
    'code': 'MO',
    'language': ['Cantonese'],
    'nationality': 'Macau',
  },
  {
    'name': 'Macedonia, The Former Yugoslav Republic of',
    'dial_code': '+389',
    'code': 'MK',
    'language': ['Macedonian'],
    'nationality': 'Macedonian',
  },
  {
    'name': 'Madagascar',
    'dial_code': '+261',
    'code': 'MG',
    'language': ['Malagasy'],
    'nationality': 'Malagasy',
  },
  {
    'name': 'Malawi',
    'dial_code': '+265',
    'code': 'MW',
    'language': ['Chichewa'],
    'nationality': 'Malawian',
  },
  {
    'name': 'Malaysia',
    'dial_code': '+60',
    'code': 'MY',
    'language': ['Bahasa Malaysia'],
    'nationality': 'Malaysian',
  },
  {
    'name': 'Maldives',
    'dial_code': '+960',
    'code': 'MV',
    'language': ['Maldivian'],
    'nationality': 'Maldivan',
  },
  {
    'name': 'Mali',
    'dial_code': '+223',
    'code': 'ML',
    'language': ['Bambara'],
    'nationality': 'Malian',
  },
  {
    'name': 'Malta',
    'dial_code': '+356',
    'code': 'MT',
    'language': ['Maltese'],
    'nationality': 'Maltese',
  },
  {
    'name': 'Marshall Islands',
    'dial_code': '+692',
    'code': 'MH',
    'language': <String>[],
    'nationality': 'Marshallese',
  },
  {
    'name': 'Martinique',
    'dial_code': '+596',
    'code': 'MQ',
    'language': <String>[],
    'nationality': 'Martinican',
  },
  {
    'name': 'Mauritania',
    'dial_code': '+222',
    'code': 'MR',
    'language': ['Arabic - MR'],
    'nationality': 'Mauritanian',
  },
  {
    'name': 'Mauritius',
    'dial_code': '+230',
    'code': 'MU',
    'language': ['Mauritian Creole'],
    'nationality': 'Mauritian',
  },
  {
    'name': 'Mayotte',
    'dial_code': '+262',
    'code': 'YT',
    'language': <String>[],
    'nationality': 'Mahoran',
  },
  {
    'name': 'Mexico',
    'dial_code': '+52',
    'code': 'MX',
    'language': ['Spanish - MX'],
    'nationality': 'Mexican',
  },
  {
    'name': 'Micronesia, Federated States of',
    'dial_code': '+691',
    'code': 'FM',
    'language': ['Micronesian'],
    'nationality': 'Micronesian',
  },
  {
    'name': 'Moldova, Republic of',
    'dial_code': '+373',
    'code': 'MD',
    'language': ['Romanian'],
    'nationality': 'Moldovan',
  },
  {
    'name': 'Monaco',
    'dial_code': '+377',
    'code': 'MC',
    'language': <String>[],
    'nationality': 'Monacan',
  },
  {
    'name': 'Mongolia',
    'dial_code': '+976',
    'code': 'MN',
    'language': ['Khalkha Mongolian'],
    'nationality': 'Mongolian',
  },
  {
    'name': 'Montenegro',
    'dial_code': '+382',
    'code': 'ME',
    'language': ['Serbian', 'Bosnian', 'Albanian'],
    'nationality': 'Montenegrin',
  },
  {
    'name': 'Montserrat',
    'dial_code': '+1664',
    'code': 'MS',
    'language': <String>[],
    'nationality': 'Montserratian',
  },
  {
    'name': 'Morocco',
    'dial_code': '+212',
    'code': 'MA',
    'language': ['Arabic - MA', 'Berber'],
    'nationality': 'Moroccan',
  },
  {
    'name': 'Mozambique',
    'dial_code': '+258',
    'code': 'MZ',
    'language': ['Portuguese - MZ'],
    'nationality': 'Mozambican',
  },
  {
    'name': 'Myanmar',
    'dial_code': '+95',
    'code': 'MM',
    'language': ['Burmese'],
    'nationality': 'Burmese',
  },
  {
    'name': 'Namibia',
    'dial_code': '+264',
    'code': 'NA',
    'language': ['Herero'],
    'nationality': 'Namibian',
  },
  {
    'name': 'Nauru',
    'dial_code': '+674',
    'code': 'NR',
    'language': ['Nauruan'],
    'nationality': 'Nauruan',
  },
  {
    'name': 'Nepal',
    'dial_code': '+977',
    'code': 'NP',
    'language': ['Nepali'],
    'nationality': 'Nepalese',
  },
  {
    'name': 'Netherlands',
    'dial_code': '+31',
    'code': 'NL',
    'language': ['Dutch'],
    'nationality': 'Dutch',
  },
  {
    'name': 'Netherlands Antilles',
    'dial_code': '+599',
    'code': 'AN',
    'language': <String>[],
    'nationality': 'Netherlands Antilles',
  },
  {
    'name': 'New Caledonia',
    'dial_code': '+687',
    'code': 'NC',
    'language': <String>[],
    'nationality': 'New Caledonian',
  },
  {
    'name': 'New Zealand',
    'dial_code': '+64',
    'code': 'NZ',
    'language': ['English - NZ', 'Maori'],
    'nationality': 'New Zealander',
  },
  {
    'name': 'Nicaragua',
    'dial_code': '+505',
    'code': 'NI',
    'language': <String>[],
    'nationality': 'Nicaraguan',
  },
  {
    'name': 'Niger',
    'dial_code': '+227',
    'code': 'NE',
    'language': ['French - NE'],
    'nationality': 'Nigerian',
  },
  {
    'name': 'Nigeria',
    'dial_code': '+234',
    'code': 'NG',
    'language': <String>[],
    'nationality': 'Nigerian',
  },
  {
    'name': 'Niue',
    'dial_code': '+683',
    'code': 'NU',
    'language': <String>[],
    'nationality': 'Niuean',
  },
  {
    'name': 'Norfolk Island',
    'dial_code': '+672',
    'code': 'NF',
    'language': <String>[],
    'nationality': 'Norfolk Islander',
  },
  {
    'name': 'Northern Mariana Islands',
    'dial_code': '+1670',
    'code': 'MP',
    'language': ['Chamorro'],
    'nationality': 'Northern Mariana Islander',
  },
  {
    'name': 'Norway',
    'dial_code': '+47',
    'code': 'NO',
    'language': ['Norwegian'],
    'nationality': 'Norwegian',
  },
  {
    'name': 'Oman',
    'dial_code': '+968',
    'code': 'OM',
    'language': ['Arabic - OM'],
    'nationality': 'Omani',
  },
  {
    'name': 'Pakistan',
    'dial_code': '+92',
    'code': 'PK',
    'language': ['Urdu'],
    'nationality': 'Pakistani',
  },
  {
    'name': 'Palau',
    'dial_code': '+680',
    'code': 'PW',
    'language': <String>[],
    'nationality': 'Palauan',
  },
  {
    'name': 'Palestinian Territory, Occupied',
    'dial_code': '+970',
    'code': 'PS',
    'language': <String>[],
    'nationality': 'Palestinian',
  },
  {
    'name': 'Panama',
    'dial_code': '+507',
    'code': 'PA',
    'language': <String>[],
    'nationality': 'Panamanian',
  },
  {
    'name': 'Papua New Guinea',
    'dial_code': '+675',
    'code': 'PG',
    'language': <String>[],
    'nationality': 'Papua New Guinean',
  },
  {
    'name': 'Paraguay',
    'dial_code': '+595',
    'code': 'PY',
    'language': ['Guarani'],
    'nationality': 'Paraguayan',
  },
  {
    'name': 'Peru',
    'dial_code': '+51',
    'code': 'PE',
    'language': ['Quechua', 'Aymara'],
    'nationality': 'Peruvian',
  },
  {
    'name': 'Philippines',
    'dial_code': '+63',
    'code': 'PH',
    'language': ['Tagalog'],
    'nationality': 'Filipino',
  },
  {
    'name': 'Pitcairn',
    'dial_code': '+872',
    'code': 'PN',
    'language': <String>[],
    'nationality': 'Pitcairn Islander',
  },
  {
    'name': 'Poland',
    'dial_code': '+48',
    'code': 'PL',
    'language': ['Polish'],
    'nationality': 'Polish',
  },
  {
    'name': 'Portugal',
    'dial_code': '+351',
    'code': 'PT',
    'language': ['Portuguese - PT'],
    'nationality': 'Portuguese',
  },
  {
    'name': 'Puerto Rico',
    'dial_code': '+1939',
    'code': 'PR',
    'language': <String>[],
    'nationality': 'Puerto Rican',
  },
  {
    'name': 'Qatar',
    'dial_code': '+974',
    'code': 'QA',
    'language': ['Arabic - QA'],
    'nationality': 'Qatari',
  },
  {
    'name': 'Réunion',
    'dial_code': '+262',
    'code': 'RE',
    'language': <String>[],
    'nationality': 'Réunionese',
  },
  {
    'name': 'Romania',
    'dial_code': '+40',
    'code': 'RO',
    'language': ['Romanian'],
    'nationality': 'Romanian',
  },
  {
    'name': 'Russian Federation',
    'dial_code': '+7',
    'code': 'RU',
    'language': ['Russian'],
    'nationality': 'Russian',
  },
  {
    'name': 'Rwanda',
    'dial_code': '+250',
    'code': 'RW',
    'language': ['Kinyarwanda'],
    'nationality': 'Rwandan',
  },
  {
    'name': 'Saint Barthélemy',
    'dial_code': '+590',
    'code': 'BL',
    'language': <String>[],
    'nationality': 'Saint Barthélemy Islander',
  },
  {
    'name': 'Saint Helena, Ascension and Tristan Da Cunha',
    'dial_code': '+290',
    'code': 'SH',
    'language': <String>[],
    'nationality': 'Saint Helenian',
  },
  {
    'name': 'Saint Kitts and Nevis',
    'dial_code': '+1869',
    'code': 'KN',
    'language': <String>[],
    'nationality': 'Kittitian',
  },
  {
    'name': 'Saint Lucia',
    'dial_code': '+1758',
    'code': 'LC',
    'language': <String>[],
    'nationality': 'Saint Lucian',
  },
  {
    'name': 'Saint Martin',
    'dial_code': '+590',
    'code': 'MF',
    'language': <String>[],
    'nationality': 'Saint-Martinoise',
  },
  {
    'name': 'Saint Pierre and Miquelon',
    'dial_code': '+508',
    'code': 'PM',
    'language': <String>[],
    'nationality': 'Saint-Pierrais',
  },
  {
    'name': 'Saint Vincent and the Grenadines',
    'dial_code': '+1784',
    'code': 'VC',
    'language': <String>[],
    'nationality': 'Saint Vincentian',
  },
  {
    'name': 'Samoa',
    'dial_code': '+685',
    'code': 'WS',
    'language': <String>[],
    'nationality': 'Samoan',
  },
  {
    'name': 'San Marino',
    'dial_code': '+378',
    'code': 'SM',
    'language': <String>[],
    'nationality': 'San Marino',
  },
  {
    'name': 'Sao Tome and Principe',
    'dial_code': '+239',
    'code': 'ST',
    'language': <String>[],
    'nationality': 'Sao Tomean',
  },
  {
    'name': 'Saudi Arabia',
    'dial_code': '+966',
    'code': 'SA',
    'language': ['Arabic - SA'],
    'nationality': 'Saudi',
  },
  {
    'name': 'Senegal',
    'dial_code': '+221',
    'code': 'SN',
    'language': ['French - SN'],
    'nationality': 'Senegalese',
  },
  {
    'name': 'Serbia',
    'dial_code': '+381',
    'code': 'RS',
    'language': ['Serbian'],
    'nationality': 'Serbian',
  },
  {
    'name': 'Seychelles',
    'dial_code': '+248',
    'code': 'SC',
    'language': ['Seselwa'],
    'nationality': 'Seychellois',
  },
  {
    'name': 'Sierra Leone',
    'dial_code': '+232',
    'code': 'SL',
    'language': <String>[],
    'nationality': 'Sierra Leonean',
  },
  {
    'name': 'Singapore',
    'dial_code': '+65',
    'code': 'SG',
    'language': ['Chinese - SG'],
    'nationality': 'Singaporean',
  },
  {
    'name': 'Slovakia',
    'dial_code': '+421',
    'code': 'SK',
    'language': ['Slovak'],
    'nationality': 'Slovak',
  },
  {
    'name': 'Slovenia',
    'dial_code': '+386',
    'code': 'SI',
    'language': ['Slovenian'],
    'nationality': 'Slovene',
  },
  {
    'name': 'Solomon Islands',
    'dial_code': '+677',
    'code': 'SB',
    'language': <String>[],
    'nationality': 'Solomon Islander',
  },
  {
    'name': 'Somalia',
    'dial_code': '+252',
    'code': 'SO',
    'language': ['Somali'],
    'nationality': 'Somali',
  },
  {
    'name': 'South Africa',
    'dial_code': '+27',
    'code': 'ZA',
    'language': ['Afrikaans'],
    'nationality': 'South African',
  },
  {
    'name': 'South Sudan',
    'dial_code': '+211',
    'code': 'SS',
    'language': <String>[],
    'nationality': 'South Sudanese',
  },
  {
    'name': 'Spain',
    'dial_code': '+34',
    'code': 'ES',
    'language': ['Spanish - ES'],
    'nationality': 'Spanish',
  },
  {
    'name': 'Sri Lanka',
    'dial_code': '+94',
    'code': 'LK',
    'language': ['Sinhala'],
    'nationality': 'Sri Lankan',
  },
  {
    'name': 'Sudan',
    'dial_code': '+249',
    'code': 'SD',
    'language': ['Arabic - SD'],
    'nationality': 'Sudanese',
  },
  {
    'name': 'Suriname',
    'dial_code': '+597',
    'code': 'SR',
    'language': ['Dutch'],
    'nationality': 'Surinamese',
  },
  {
    'name': 'Svalbard and Jan Mayen',
    'dial_code': '+47',
    'code': 'SJ',
    'language': <String>[],
    'nationality': 'Svalbard',
  },
  {
    'name': 'Swaziland',
    'dial_code': '+268',
    'code': 'SZ',
    'language': ['Swazi'],
    'nationality': 'Swazi',
  },
  {
    'name': 'Sweden',
    'dial_code': '+46',
    'code': 'SE',
    'language': ['Swedish'],
    'nationality': 'Swedish',
  },
  {
    'name': 'Switzerland',
    'dial_code': '+41',
    'code': 'CH',
    'language': ['German - CH'],
    'nationality': 'Swiss',
  },
  {
    'name': 'Syrian Arab Republic',
    'dial_code': '+963',
    'code': 'SY',
    'language': ['Arabic - SY'],
    'nationality': 'Syrian',
  },
  {
    'name': 'Taiwan',
    'dial_code': '+886',
    'code': 'TW',
    'language': ['Chinese - TW'],
    'nationality': 'Taiwanese',
  },
  {
    'name': 'Tajikistan',
    'dial_code': '+992',
    'code': 'TJ',
    'language': ['Tajik'],
    'nationality': 'Tajik',
  },
  {
    'name': 'Tanzania, United Republic of',
    'dial_code': '+255',
    'code': 'TZ',
    'language': ['Kiswahili'],
    'nationality': 'Tanzanian',
  },
  {
    'name': 'Thailand',
    'dial_code': '+66',
    'code': 'TH',
    'language': ['Thai'],
    'nationality': 'Thai',
  },
  {
    'name': 'Timor-Leste',
    'dial_code': '+670',
    'code': 'TL',
    'language': <String>[],
    'nationality': 'Timorese',
  },
  {
    'name': 'Togo',
    'dial_code': '+228',
    'code': 'TG',
    'language': <String>[],
    'nationality': 'Togolese',
  },
  {
    'name': 'Tokelau',
    'dial_code': '+690',
    'code': 'TK',
    'language': <String>[],
    'nationality': 'Tokelauan',
  },
  {
    'name': 'Tonga',
    'dial_code': '+676',
    'code': 'TO',
    'language': <String>[],
    'nationality': 'Tongan',
  },
  {
    'name': 'Trinidad and Tobago',
    'dial_code': '+1868',
    'code': 'TT',
    'language': <String>[],
    'nationality': 'Trinidadian',
  },
  {
    'name': 'Tunisia',
    'dial_code': '+216',
    'code': 'TN',
    'language': ['Arabic - TN'],
    'nationality': 'Tunisian',
  },
  {
    'name': 'Turkey',
    'dial_code': '+90',
    'code': 'TR',
    'language': ['Turkish'],
    'nationality': 'Turkish',
  },
  {
    'name': 'Turkmenistan',
    'dial_code': '+993',
    'code': 'TM',
    'language': ['Turkmen'],
    'nationality': 'Turkmen',
  },
  {
    'name': 'Turks and Caicos Islands',
    'dial_code': '+1649',
    'code': 'TC',
    'language': <String>[],
    'nationality': 'Turks and Caicos Islander',
  },
  {
    'name': 'Tuvalu',
    'dial_code': '+688',
    'code': 'TV',
    'language': <String>[],
    'nationality': 'Tuvaluan',
  },
  {
    'name': 'Uganda',
    'dial_code': '+256',
    'code': 'UG',
    'language': ['Luganda'],
    'nationality': 'Ugandan',
  },
  {
    'name': 'Ukraine',
    'dial_code': '+380',
    'code': 'UA',
    'language': ['Ukrainian'],
    'nationality': 'Ukrainian',
  },
  {
    'name': 'United Arab Emirates',
    'dial_code': '+971',
    'code': 'AE',
    'language': ['Arabic - AE'],
    'nationality': 'Emirati',
  },
  {
    'name': 'United Kingdom',
    'dial_code': '+44',
    'code': 'GB',
    'language': ['English - GB'],
    'nationality': 'British',
  },
  {
    'name': 'United States',
    'dial_code': '+1',
    'code': 'US',
    'language': ['English - US', 'Spanish - US'],
    'nationality': 'American',
  },
  {
    'name': 'Uruguay',
    'dial_code': '+598',
    'code': 'UY',
    'language': ['Spanish - UY'],
    'nationality': 'Uruguayan',
  },
  {
    'name': 'Uzbekistan',
    'dial_code': '+998',
    'code': 'UZ',
    'language': ['Uzbek'],
    'nationality': 'Uzbekistani',
  },
  {
    'name': 'Vanuatu',
    'dial_code': '+678',
    'code': 'VU',
    'language': <String>[],
    'nationality': 'Vanuatuan',
  },
  {
    'name': 'Venezuela, Bolivarian Republic of',
    'dial_code': '+58',
    'code': 'VE',
    'language': ['Spanish - VE'],
    'nationality': 'Venezuelan',
  },
  {
    'name': 'Viet Nam',
    'dial_code': '+84',
    'code': 'VN',
    'language': ['Vietnamese'],
    'nationality': 'Vietnamese',
  },
  {
    'name': 'Virgin Islands, British',
    'dial_code': '+1284',
    'code': 'VG',
    'language': <String>[],
    'nationality': 'British Virgin Islander',
  },
  {
    'name': 'Virgin Islands, U.S.',
    'dial_code': '+1340',
    'code': 'VI',
    'language': <String>[],
    'nationality': 'U.S. Virgin Islander',
  },
  {
    'name': 'Wallis and Futuna',
    'dial_code': '+681',
    'code': 'WF',
    'language': <String>[],
    'nationality': 'Wallis and Futuna Islander',
  },
  {
    'name': 'Yemen',
    'dial_code': '+967',
    'code': 'YE',
    'language': ['Arabic - YE'],
    'nationality': 'Yemeni',
  },
  {
    'name': 'Zambia',
    'dial_code': '+260',
    'code': 'ZM',
    'language': <String>[],
    'nationality': 'Zambian',
  },
  {
    'name': 'Zimbabwe',
    'dial_code': '+263',
    'code': 'ZW',
    'language': ['Shona', 'Ndebele'],
    'nationality': 'Zimbabwean',
  }
];




